// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from "./src/config/env";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DB_URL
  },
});
